SELECT * FROM oyo.bookings;

#total revenue generated by each city
SELECT 
	City,
    SUM(Room_Price * number_of_nights) as total_revenue
FROM oyo.bookings
GROUP BY City;

#customers who made more than 3 bookings in the last year
SELECT
	customer_id,
    COUNT(booking_id) as total_booking
FROM oyo.bookings
WHERE Year(booking_date) = Year(date_add(curdate() , INTERVAL -1 YEAR))
GROUP BY customer_id
HAVING total_booking>3;

#cancellation rate for each property
SELECT
		property_id,
        ROUND( SUM(IF(booking_status = 'cancelled', 1, 0)) * 100/ COUNT(booking_status), 2) as pct_cancellation
FROM oyo.bookings
GROUP By property_id;

#month with the highest revenue for each city
WITH CTE AS( SELECT City, 
		month(booking_date) as BMonth,
        SUM(room_price * number_of_nights) as Revenue,
        RANK() OVER(partition by city order by sum(room_price*number_of_nights) desc) as Rank1
FROM oyo.bookings
GROUP BY City, Month(booking_date))

SELECT City, BMonth, Revenue
FROM CTE
WHERE Rank1 = 1;


#properties with occupancy rates greater than 90%. Assume a properties table with columns: property_id, total_rooms, and occupied_rooms
SELECT property_id,
		(occupied_rooms*100)/total_rooms as occupany_rate
from oyo.bookings_properties
GROUP BY property_id
HAVING occupany_rate> 90.0;

